import path from "node:path";
import { headers } from "next/headers";
import { type NextRequest, NextResponse } from "next/server";
import PDFDocument from "pdfkit";
import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import { utapi } from "@/lib/files";

interface RouteParams {
  params: Promise<{ id: string }>;
}

export async function POST(request: NextRequest, { params }: RouteParams) {
  const session = await auth.api.getSession({ headers: await headers() });

  if (!session?.user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  // Rate limit check for AI generation
  const { ajAI } = await import("@/lib/arcjet");
  const decision = await ajAI.protect(request, {
    userId: session.user.id,
    requested: 1,
  });
  if (decision.isDenied()) {
    return NextResponse.json(
      { error: "Rate limit exceeded. Please try again later." },
      { status: 429 },
    );
  }

  const { id } = await params;

  // Fetch full idea data
  const idea = await db.idea.findUnique({
    where: { id },
    include: {
      scores: { orderBy: { createdAt: "desc" }, take: 1 },
      researchPackets: true,
    },
  });

  if (!idea) {
    return NextResponse.json({ error: "Idea not found" }, { status: 404 });
  }

  if (idea.userId !== session.user.id) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  // Create PDF
  const doc = new PDFDocument({ margin: 50 });
  doc.registerFont(
    "Inter",
    path.join(process.cwd(), "public/fonts/Nunito-VariableFont_wght.ttf"),
  );

  const chunks: Buffer[] = [];

  doc.on("data", (chunk) => chunks.push(chunk));

  // Header
  doc
    .fontSize(24)
    .font("Helvetica-Bold")
    .text(idea.title || "Untitled Idea", { align: "center" })
    .moveDown(0.5);

  doc
    .fontSize(12)
    .font("Helvetica")
    .text("Generated by IdeasVault AI", {
      align: "center",
      color: "grey",
    } as any)
    .moveDown(2);

  // Summary
  doc
    .fontSize(16)
    .font("Helvetica-Bold")
    .text("Executive Summary", { color: "black" } as any)
    .moveDown(0.5);

  doc
    .fontSize(12)
    .font("Helvetica")
    .text(idea.summary || "No summary available")
    .moveDown(2);

  // Scores
  if (idea.scores[0]) {
    const score = idea.scores[0];
    doc
      .fontSize(16)
      .font("Helvetica-Bold")
      .text("AI Assessment Scores")
      .moveDown(0.5);

    doc.fontSize(12).font("Helvetica");
    doc.text(`Overall Score: ${score.overallScore}/100`);
    doc.text(`Clarity: ${score.clarityScore}/100`);
    doc.text(`Market Readiness: ${score.marketScore}/100`);
    doc.text(`Execution Feasibility: ${score.executionScore}/100`);
    doc.moveDown(2);
  }

  // Research Content
  const synthesis = idea.researchPackets.find(
    (p) => p.agentType === "SYNTHESIS",
  )?.content as any;
  if (synthesis) {
    doc.fontSize(16).font("Helvetica-Bold").text("Final Verdict").moveDown(0.5);

    doc
      .fontSize(12)
      .font("Helvetica-Bold")
      .text(`Verdict: ${synthesis.verdict.replace(/-/g, " ").toUpperCase()}`)
      .moveDown(0.5);

    doc.font("Helvetica").text(synthesis.overallAssessment).moveDown(2);

    if (synthesis.recommendations) {
      doc
        .fontSize(14)
        .font("Helvetica-Bold")
        .text("Key Recommendations")
        .moveDown(0.5);

      synthesis.recommendations.forEach((rec: any) => {
        doc
          .fontSize(12)
          .font("Helvetica-Bold")
          .text(`• [${rec.priority.toUpperCase()}] ${rec.action}`)
          .font("Helvetica")
          .text(`  ${rec.rationale}`)
          .moveDown(0.5);
      });
    }
  }

  doc.end();

  // Wait for PDF generation to finish
  const pdfBuffer = await new Promise<Buffer>((resolve) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
  });

  // Upload to storage
  const filename = `research-report-${id}.pdf`;
  const file = new File([new Uint8Array(pdfBuffer)], filename, {
    type: "application/pdf",
  });

  const response = await utapi.uploadFiles([file]);

  if (response[0].error) {
    console.error("UploadThing error:", response[0].error);
    return NextResponse.json(
      { error: "Failed to upload PDF" },
      { status: 500 },
    );
  }

  const { ufsUrl } = response[0].data;

  return NextResponse.json({ url: ufsUrl });
}
