DO $$ BEGIN CREATE TYPE "LessonType" AS ENUM ('VIDEO','TEXT','QUIZ','ASSIGNMENT'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "ContentProvider" AS ENUM ('YOUTUBE','VIMEO','CUSTOM'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "EnrollmentStatus" AS ENUM ('ENROLLED','IN_PROGRESS','COMPLETED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "LessonProgressStatus" AS ENUM ('NOT_STARTED','IN_PROGRESS','COMPLETED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "SubmissionType" AS ENUM ('TEXT','FILE','LINK'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "courses" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "slug" TEXT NOT NULL, "description" TEXT, "thumbnail" TEXT, "category" TEXT, "isPublished" BOOLEAN NOT NULL DEFAULT false, "position" INTEGER NOT NULL DEFAULT 0, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "courses_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "courses_slug_key" ON "courses"("slug");
CREATE INDEX IF NOT EXISTS "courses_category_idx" ON "courses"("category");
CREATE INDEX IF NOT EXISTS "courses_isPublished_idx" ON "courses"("isPublished");
CREATE TABLE IF NOT EXISTS "course_modules" ("id" TEXT NOT NULL, "courseId" TEXT NOT NULL, "title" TEXT NOT NULL, "description" TEXT, "position" INTEGER NOT NULL DEFAULT 0, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "course_modules_pkey" PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "course_modules_courseId_idx" ON "course_modules"("courseId");
CREATE INDEX IF NOT EXISTS "course_modules_position_idx" ON "course_modules"("position");
CREATE TABLE IF NOT EXISTS "lessons" ("id" TEXT NOT NULL, "moduleId" TEXT NOT NULL, "title" TEXT NOT NULL, "description" TEXT, "type" "LessonType" NOT NULL DEFAULT 'VIDEO', "content" JSONB, "position" INTEGER NOT NULL DEFAULT 0, "duration" INTEGER, "videoUrl" TEXT, "provider" "ContentProvider" NOT NULL DEFAULT 'YOUTUBE', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "lessons_pkey" PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "lessons_moduleId_idx" ON "lessons"("moduleId");
CREATE INDEX IF NOT EXISTS "lessons_position_idx" ON "lessons"("position");
CREATE TABLE IF NOT EXISTS "enrollments" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "courseId" TEXT NOT NULL, "status" "EnrollmentStatus" NOT NULL DEFAULT 'ENROLLED', "enrolledAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "completedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "enrollments_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "enrollments_userId_courseId_key" ON "enrollments"("userId","courseId");
CREATE INDEX IF NOT EXISTS "enrollments_userId_idx" ON "enrollments"("userId");
CREATE INDEX IF NOT EXISTS "enrollments_courseId_idx" ON "enrollments"("courseId");
CREATE TABLE IF NOT EXISTS "lesson_progress" ("id" TEXT NOT NULL, "enrollmentId" TEXT NOT NULL, "lessonId" TEXT NOT NULL, "status" "LessonProgressStatus" NOT NULL DEFAULT 'NOT_STARTED', "maxPercentage" INTEGER NOT NULL DEFAULT 0, "timeSpent" INTEGER NOT NULL DEFAULT 0, "completedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "lesson_progress_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "lesson_progress_enrollmentId_lessonId_key" ON "lesson_progress"("enrollmentId","lessonId");
CREATE INDEX IF NOT EXISTS "lesson_progress_enrollmentId_idx" ON "lesson_progress"("enrollmentId");
CREATE INDEX IF NOT EXISTS "lesson_progress_lessonId_idx" ON "lesson_progress"("lessonId");
CREATE TABLE IF NOT EXISTS "quizzes" ("id" TEXT NOT NULL, "lessonId" TEXT NOT NULL, "questions" JSONB NOT NULL, "passingScore" INTEGER NOT NULL DEFAULT 70, "maxAttempts" INTEGER NOT NULL DEFAULT 3, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "quizzes_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "quizzes_lessonId_key" ON "quizzes"("lessonId");
CREATE TABLE IF NOT EXISTS "quiz_attempts" ("id" TEXT NOT NULL, "quizId" TEXT NOT NULL, "userId" TEXT NOT NULL, "score" INTEGER NOT NULL DEFAULT 0, "answers" JSONB NOT NULL, "passed" BOOLEAN NOT NULL DEFAULT false, "completedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "quiz_attempts_pkey" PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "quiz_attempts_quizId_idx" ON "quiz_attempts"("quizId");
CREATE INDEX IF NOT EXISTS "quiz_attempts_userId_idx" ON "quiz_attempts"("userId");
CREATE TABLE IF NOT EXISTS "assignments" ("id" TEXT NOT NULL, "lessonId" TEXT NOT NULL, "instructions" TEXT NOT NULL, "dueDays" INTEGER, "submissionType" "SubmissionType" NOT NULL DEFAULT 'TEXT', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "assignments_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "assignments_lessonId_key" ON "assignments"("lessonId");
CREATE TABLE IF NOT EXISTS "submissions" ("id" TEXT NOT NULL, "assignmentId" TEXT NOT NULL, "userId" TEXT NOT NULL, "content" JSONB, "grade" INTEGER, "feedback" TEXT, "submittedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "gradedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "submissions_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "submissions_assignmentId_userId_key" ON "submissions"("assignmentId","userId");
CREATE INDEX IF NOT EXISTS "submissions_assignmentId_idx" ON "submissions"("assignmentId");
CREATE INDEX IF NOT EXISTS "submissions_userId_idx" ON "submissions"("userId");
CREATE TABLE IF NOT EXISTS "certificates" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "courseId" TEXT NOT NULL, "certificateUrl" TEXT, "verificationCode" TEXT NOT NULL, "issuedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "certificates_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "certificates_verificationCode_key" ON "certificates"("verificationCode");
CREATE UNIQUE INDEX IF NOT EXISTS "certificates_userId_courseId_key" ON "certificates"("userId","courseId");
CREATE INDEX IF NOT EXISTS "certificates_userId_idx" ON "certificates"("userId");
CREATE TABLE IF NOT EXISTS "badges" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "icon" TEXT, "description" TEXT, "criteria" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "badges_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "badges_name_key" ON "badges"("name");
CREATE TABLE IF NOT EXISTS "user_badges" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "badgeId" TEXT NOT NULL, "earnedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "user_badges_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "user_badges_userId_badgeId_key" ON "user_badges"("userId","badgeId");
CREATE INDEX IF NOT EXISTS "user_badges_userId_idx" ON "user_badges"("userId");
ALTER TABLE "course_modules" ADD CONSTRAINT "course_modules_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "lessons" ADD CONSTRAINT "lessons_moduleId_fkey" FOREIGN KEY ("moduleId") REFERENCES "course_modules"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "enrollments" ADD CONSTRAINT "enrollments_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "enrollments" ADD CONSTRAINT "enrollments_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "lesson_progress" ADD CONSTRAINT "lesson_progress_enrollmentId_fkey" FOREIGN KEY ("enrollmentId") REFERENCES "enrollments"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "lesson_progress" ADD CONSTRAINT "lesson_progress_lessonId_fkey" FOREIGN KEY ("lessonId") REFERENCES "lessons"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "quizzes" ADD CONSTRAINT "quizzes_lessonId_fkey" FOREIGN KEY ("lessonId") REFERENCES "lessons"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "quiz_attempts" ADD CONSTRAINT "quiz_attempts_quizId_fkey" FOREIGN KEY ("quizId") REFERENCES "quizzes"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "quiz_attempts" ADD CONSTRAINT "quiz_attempts_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "assignments" ADD CONSTRAINT "assignments_lessonId_fkey" FOREIGN KEY ("lessonId") REFERENCES "lessons"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "submissions" ADD CONSTRAINT "submissions_assignmentId_fkey" FOREIGN KEY ("assignmentId") REFERENCES "assignments"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "submissions" ADD CONSTRAINT "submissions_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "certificates" ADD CONSTRAINT "certificates_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "certificates" ADD CONSTRAINT "certificates_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "user_badges" ADD CONSTRAINT "user_badges_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "user_badges" ADD CONSTRAINT "user_badges_badgeId_fkey" FOREIGN KEY ("badgeId") REFERENCES "badges"("id") ON DELETE CASCADE ON UPDATE CASCADE;
